### ISSUE TITLE
Email content storage design.

### ISSUE THREAD

**Issue by yli302** [yli302/SMTP_POP3_email#3]
Email content store format.
* Directory file.
```
struct Index{
    uint16_t key;
    uint16_t file_nr;
    uint32_t offset;
}
```
Key is got by system time + unique number (range from 0~9) to generate a unique Key;
* Content storage file.

1000 email for each file. 
```
format: [uid] [time] [source] [target] [subject] [content]
```

**Comment by liehuozhizun** [comment]
Write a independent design doc to address the format
